### ISSUE TITLE
CSS disappear

### ISSUE THREAD

**Issue by matunixe** [Sonerezh/sonerezh#149]
Hello there,

A new error appear recently, I just installed the last release (1.0.0) but the CSS do not work.
A few screenshots:

![screen shot 2016-01-17 at 18 12 30](https://cloud.githubusercontent.com/assets/10813340/12378680/1edf945a-bd46-11e5-9e07-978665795de9.png)
![screen shot 2016-01-17 at 18 12 49](https://cloud.githubusercontent.com/assets/10813340/12378682/210029f2-bd46-11e5-93e0-8ed754760d5d.png)
![screen shot 2016-01-17 at 18 12 57](https://cloud.githubusercontent.com/assets/10813340/12378683/25099b1e-bd46-11e5-9186-247c721217ca.png)

Cheers

**Comment by lGuillaume124** [comment]
Hmm I don't think it is a Sonerezh issue, but a wrong configuration of your web server.
What is your web server? Can we see your conf?

It seems that it is a rewrite issue because the static resources are available under ``http://music.unixcorn.org/app/webroot/`` (``http://music.unixcorn.org/app/webroot/css/bootstrap.min.css`` for example).

**Comment by lGuillaume124** [comment]
Well apparently you are using Nginx. Can you post your server-block please?

**Comment by matunixe** [comment]
Hahah, excuse-me I forget the good path: ``/app/webroot/`` !
Shame on me, thanks for your answer.
