### ISSUE TITLE
Add option to choose 'Album artist' instead of 'Artist' when parsing id3v2 tags

### ISSUE THREAD

**Issue by z0lt4n** [Sonerezh/sonerezh#176]
Hi,
it could be nice to have an option to let admin choose to parse the 'Album artist' tag field (TPE2 in id3v2), if it exists, to populate the artist column of the database instead of the 'Artist' tag (TPE1).
Main reason for this is that I have compilations, albums from music collectives, or albums which contains some remixes, but I want them to appear below the same artist in artists view.

Thanks for your work.

**Comment by MightyCreak** [comment]
It seems to already work. I have two albums for two seasons of a TV show. In the Album tag I set the season, in the Album artist tag I set the name of the TV show, and in the Artist tag I set the actual track artist.

In the artist view, all the seasons appear under the name of the TV show, there are two albums (one per season) and I can see both the title and the artist of the track.

**Comment by z0lt4n** [comment]
Hi,
it already works indeed with most of my music collection, but i still had some albums with strange behavior, so I took a look at the tags.
The problem i had come from the fact that some tracks had a non consistent (or empty) TDAT and TIME tag value. TYER was the same for all tracks : the tracks with TDAT or TIME appeared under a different artist in the "artist view", the ones with no TDAT and TIME were grouped correctly.

Anyway, thanks for your answer and your work.

**Comment by MightyCreak** [comment]
@lGuillaume124 maybe it's a bug...

Actually, I think you're right @z0lt4n. I just imported my CD rip of Pulp Fiction and I didn't add an "Album artist" because there is none. So I had that:
* Album = "Pulp Fiction"
* Album artist = "" (nothing)
* Title = title of the song
* Artist = artist of the song

So when I go to the Albums view, I think it's reasonable to see one Pulp Fiction album with all the tracks in it.

But what I had is one Pulp Fiction album with only one track in it. I could see all the other tracks of the album in the Artists view, but dispersed a bit everywhere.

Workaround: set the same value in the fields Album artist and Album.
