### ISSUE TITLE
Pre-load next song

### ISSUE THREAD

**Issue by mneute** [Sonerezh/sonerezh#179]
First, sorry if this was already asked, but i couldn't find any issue about this.

I'd really like Sonerezh to buff the next song in the playlist, since i'm using it with a poor internet connection. The songs plays just fine, but when it's over, i might have to wait 5 seconds before the next one starts.

I saw [someone made a pull request](https://github.com/Sonerezh/sonerezh/pull/114) about this, might be interesting investing it.

Thanks anyway.

**Comment by atomiix** [comment]
Hi,

I was looking for merge your PR but it seems that creating another audio element and loading the next song is not enough, the main audio element will reload the next song anyway.
In addition, it's hard to see because when using a local environment it loads songs very fast.
But in chrome, you can throttle the bandwidth speed in the developer console.

I'm still looking for a good solution to preload the next song, if you have any idea, let me know 😉

**Comment by Obenj** [comment]
Could it be possible, a minima, to transcode the next songs in cache ? On a lightweight system such as a VPS or a RaspberryPi, transcoding time is not negligeable (5 to 10 s) ?

Great project by the way ! Replaces very well Deezer for my use ! Glad to see that there is a efficient and free alternative that is built : the old solutions like Ampache are quite ageing ! ;)
