### ISSUE TITLE
Translator

### ISSUE THREAD

**Issue by BoneAsh** [Sonerezh/sonerezh#184]
how can i change the language to the Chinese?
which file should i change?

**Comment by BoneAsh** [comment]
there are many users in china,i think you can fix chinese language,thx

**Comment by lGuillaume124** [comment]
Hi,

The app has not been translated into Chinese. Feel free to do it and propose a pull request.

Sonerezh is ready to be translated into any language because we use the internationalization functions built in CakePHP.

**How does it work?**
It works like a dictionary, in which the reference is the English. Then you can associate each english word or sentence to the translated one, and create the new dictionary corresponding to your language.

The default catalog is stored into ``app/Locale/default.po``.

**How to do this?**
In ``app/Locale`` you can already see two folders: 

- ``eng``: the English translation
- ``fra``: the French translation

You can use [Poedit](https://poedit.net/) to create the chinese catalog. Once you have installed it, go to Files, "New catalog from a POT file" and select ``app/Locale/default.po``. Then you can translate every expression found into the app.

When the translation is done, you can save your work into ``app/Locale/chi/LC_MESSAGES/default.po`` and send your pull request, we will integrate it into Sonerezh.

You can also find documentation on [the CakePHP CookBook](http://book.cakephp.org/2.0/en/core-libraries/internationalization-and-localization.html#internationalizing-your-application). We would be happy to propose a Chinese version of Sonerezh.
