### ISSUE TITLE
Command line tool

### ISSUE THREAD

**Issue by Knah-Tsaeb** [Sonerezh/sonerezh#2]
Hi,
I have big music collection and I can't import my library with fronted app (memory limit + max execution time). Can you add command line tool for import and maintain database ?

**Comment by Knah-Tsaeb** [comment]
I try to split my collection for multiple import, but that's not working. I change max_memory_limit for 8g but not working (PHP Fatal error:  Allowed memory size of 8589934592 bytes exhausted). I think the import method is not adapt for large library.

**Comment by lGuillaume124** [comment]
Hi,

Thanks for your feedback.

Please be patient, we will review your problem as soon as possible. The import script works for my library, I have more than 12 000 files.

**Comment by Knah-Tsaeb** [comment]
No problem, I just report my problem for make better apps as possible.

Thansk for your work.

**Comment by Knah-Tsaeb** [comment]
Ok i open new issue for memory limit #23.

But i think command line tool can be a good idea for updating database with cron for example.

**Comment by lGuillaume124** [comment]
A command line tool could be a good feature, but it's not a priority for the moment.

We let the issue opened for future releases ;)

**Comment by DiscoSeb** [comment]
Hi,
I created with AutoIt, a command line program (for Windows) to import my MP3 directly into the database
Currently I run it manually, but you should be able to integrate it into sonerezh.
If you want, I can share it...

**Comment by lGuillaume124** [comment]
Hi, why not! Will be glad to see your work :)

**Comment by erdnuesse** [comment]
Voting for #Bug because not being able to import your library because of too many audio files to process in 30 seconds should be considered as bug, not enhancement. 
Bug = unable to get things to work
Enhancement = working environment, can be improved
More than 500G of music is quite a lot, but should be manageable. For smaller collections, there are plenty of solutions - the larger the collection, the greater the need for centralized management and streaming abilities like this. (for a 40G collection i'd simply sync everything onto a player like ipod, stream over google play music or sync via owncloud and play always locally.)

**Comment by lGuillaume124** [comment]
Added on the roadmap: http://roadmap.sonerezh.bzh/b/eCuz4jyhwjmxpxX8C/sonerezh-roadmap
