### ISSUE TITLE
Browse music using the existing directory structure

### ISSUE THREAD

**Issue by nodiscc** [Sonerezh/sonerezh#28]
My music directory is well organized; I like sonerezh's library view so far, but I'd appreciate being able to browse files/folders just like I do on my local file system. 

Manual filesystem-based organization allows sorting tracks/albums in non-standard ways (compilations, genre-based directories, ...), allows specifying custom thumbnails (folder.jpg), amongst other advantages.

Think it could be doable?

Thanks again this project rocks

**Comment by lGuillaume124** [comment]
Hi,

Thanks for the feedback!
We have not planned to allow this. You can create compilations with playlists, and we will work on a filter system for each view (filter by date, filter by albumn etc).

**Comment by GLLM** [comment]
I was going to book a same issue as noddisc : 
* browse by folder : since I'm a bit of a maniac, my library os really well organized ... I love folders more anything else
* browser by genre 

The browser by folder makes sense when you have, like me, thousands of tunes coming mostly from singles/releases and seldom albums (electronic music).

FYI my sonerezh instance tells me I have 3627 artists and 5093 albums ... so browsing by albums or artist is really not handy.

Oh yes, 98% of my library is properly tagged with label + release info, cover, genre, year ...
So my request is not because I'm not organized :)

Too bad !

**Comment by nodiscc** [comment]
It seems @GLLM and I are on the same boat. Using a library view needs good organization/tagging. My tags are in very decent order thanks to automated tools like [beets](http://beets.radbox.org/) and musicbrainz integration in tagging tools. But songs from random sources (check the README of [this project](https://github.com/nodiscc/shaarchiver) which I use a lot) are simply impossible to tag properly without spending a huge amount of time on it. Most people will simply never use tagging.

@lGuillaume124 @atomiix would you be ok reconsidering this? Is a folder-based view hard to implement over the existing codebase?

**Comment by lGuillaume124** [comment]
Sorry but we won't. It implies too many changes in the source code and would require too many time to be implemented. We are two students with a lot of others projetcs...

**Comment by GLLM** [comment]
@lGuillaume124 : I can understand your point for the folder browsing.
On the other hand, genre is just another standard tag from MP3.
I guess it should be quite close to your model, doesn't it ?
