### ISSUE TITLE
Use "Album artist" tag instead of "Artist" for sorting

### ISSUE THREAD

**Issue by nodiscc** [Sonerezh/sonerezh#30]
Hi again; I'm having a problem with artist-based sorting (a problem which is common to many music library software): albums featuring multiple artists appear scattered around the library, because each track has a different `Artist` tag field (eg [this album](http://musicbrainz.org/release/a43ea649-a156-35f7-b807-a6e72f9b2e34)).

Both ID3 and OGG tags have an `Album artist` field which is used to group artists/composers into a single "band" name (eg for this album the `Album artist` field is `Thievery Corporation`), making them easier to find in a large library.

Currently my Thievery Corporation albums are scattered throughout 15-20 different artists, some artists in the library only have 1 track because of this.

Can you use the `Album artist` field to do the sorting, or at least provide a switch to use it when available?

Thanks

**Comment by lGuillaume124** [comment]
Hi,

What tool did you use to mark your files?

**Comment by nodiscc** [comment]
@lGuillaume124 I use several tools depending on the task. For batch tagging of LOTS of files, I use [beets](http://beets.radbox.org/). For tagging/cleanup of a single album/few files, I use [ExFalso](http://quodlibet.readthedocs.org/en/latest/guide/editing_tags.html) or Easytag. Both tools use the [Musicbrainz](http://musicbrainz.org/) database to fetch song/album info and populate the ID3/OGG/FLAC tags.

**Comment by lGuillaume124** [comment]
Because I think your files are just badly tagged. The tag you mentionned (`Album artist`) is in fact called `Band`. And Sonerezh look for this tag to sort the songs.

Here an output example for one of my song: 

![metadata](https://cloud.githubusercontent.com/assets/3330841/6484036/60bf85a2-c278-11e4-892c-05214f3bb116.png)

And what it looks like in Sonerezh:

![metadata2](https://cloud.githubusercontent.com/assets/3330841/6483996/da977e44-c277-11e4-8ead-95ff3ec7fd03.png)

**Comment by nodiscc** [comment]
Sorry for the noise, you were right and some files were improperly tagged (`artist` and `band` fields were the same). Great album by the way.
