### ISSUE TITLE
A "Listener" can update any account

### ISSUE THREAD

**Issue by mneute** [Sonerezh/sonerezh#33]
As a listener, simply go to /users/edit/*id* and you can edit any account.

**Comment by pikzen** [comment]
What the fuck. It actually works.

What's even worse is that you can change any user's password **without verification** ! So basically, edit user 1 which will most likely be the admin and it's done.
Ok, this is limited to people you registered on, but this also means that Sonerezh cannot be used as a service with an open registration because the abuse potential is massive.

**Comment by lGuillaume124** [comment]
That's exactly why this is a [**beta release**](https://en.wikipedia.org/wiki/Software_release_life_cycle#Beta).
