### ISSUE TITLE
Not Found - The requested URL /sonerezh/install was not found on this server.

### ISSUE THREAD

**Issue by Nico207** [Sonerezh/sonerezh#41]
Bonjour,

j'ai suivi les instructions de la documentation (https://www.sonerezh.bzh/docs/fr/installation.html) sur deux serveurs dédiés. 
A chaque fois, l'accès à l'URL http://monsite,fr/sonerezh redirige vers l'adresse http://monsite,fr/install

Cependant, le message d'erreur suivant apparaît :
> Not Found
> The requested URL /sonerezh/install was not found on this server.

Tous les dossiers et fichiers sont bien avec un chmod 775 et un chown à www-data:www-data
Le répertoire ./sonerezh/app/tmp existe bien (il contient 2 répertoires et plusieurs sous-répertoires)

**Système :**
Ubuntu 14.04 64bits
Apache 2.4.7
PHP 5.5.9 (module php5-gd activé)

**Comment by p1rox** [comment]
Tu n'as pas activé l'URL rewriting d'Apache

**Comment by Nico207** [comment]
Effectivement... 
Peut-être ajouter cette commande dans la doc de configuration ?

Désolé pour le dérangement et merci beaucoup.

**Comment by siger95** [comment]
I checked all my settings and all is OK , I use the 1.1.1 version of sonerezh and I still have this document not found problem. I can't install sonerezh because of this. I already used it once and it is a great software. 

J'ai vérifié ma configuration et tout est bon. Pourtant j'ai toujours l'erreur "document not found". J'utilise la version 1.1.1 avec apache sur un raspberry pi. Je ne peux pas installer Sonerezh. Dommage parceque je l'ai installé une première fois avec succès et il est super. 

Est ce que ça vient de l'application ? Est ce une précison à ajouter dans la documentation ? 

Merci
