### ISSUE TITLE
Better Responsive and Mobile support

### ISSUE THREAD

**Issue by AC10** [Sonerezh/sonerezh#56]
Sonerezh is exactly what I've been looking for quite some time!
So thanks for making it!

But I have one small suggestion, make it more mobile friendly.
The responsive design is OK I guess, there's some things that doesn't work to well, but it works.. 
The icons in the menu is very small, the song list is outside the view port, and the play/pause, next and prev buttons is up and down on each other

But what doesn't work, is the player itself. I can't play music through my phone!
It's annoying.

Every time I tap on the play icon on a song, artist or playlist, it shows the song title in the player, shows minutes, but then refreshes the page, and then it's gone. Now I can tap the play icon again, and the exact same thing happens!

**Comment by nodiscc** [comment]
> Every time I tap on the play icon on a song, artist or playlist, it shows the song title in the player, shows minutes, but then refreshes the page, and then it's gone

Looks like the same issue as https://github.com/Sonerezh/sonerezh/issues/53. Note that your browser has to support HTML5 audio, and have an available codec for the format you're trying to decode.

 * What browser/OS are you using?
 * What are the results in the Audio/Codecs section of https://html5test.com/ using this browser
 * What is the format of the file you're trying to play?

This issue is not about responsive design at all, you should change the title.

**Comment by lGuillaume124** [comment]
We know that we have an issue on Android. The first priority is to develop a robust API, and then a native application.

**Comment by nodiscc** [comment]
> a native application.

What's the reasoning behind this? Are you going to develop apps for every mobile OS? The web UI app is standards-compliant and displays well on any screen factor. This can be discussed elsewhere but I think you'd better not waste your time (which you seem to be short on :) )

**Comment by AC10** [comment]
@nodiscc This is issue is about BOTH respomsive design, and the functionality.

Also, I'm running Android 5.0.1
Using Firefox Mobile 36.0
And it scores 456, and supports everything that is needed.
Aaaaand the format is MP3.


@lGuillaume124 Okay, great!

**Comment by lGuillaume124** [comment]
> What's the reasoning behind this?

A native application could propose new features like offline mode or the transfer of a current play from a device to another, etc. Imagine you are on your way home and you are listening music with Sonerezh Android application. When you arrive at home you could say to your device: "transfer the current play to my computer", and the Sonerezh webapp could resume the song.

**Comment by atomiix** [comment]
Well, we can try to fix the android player issue because yes, that should work, but we won't focus on responsive design.

**Comment by AC10** [comment]
@atomiix Okay, well, if you're planning a native app, it's even better than fixing the issue in the webapp. So it's just great!

But I still think you should work on the responsive design, or I maybe look at it myself and make a pull request later

**Comment by asmartin** [comment]
Regarding a mobile app, you might want to consider implementing the [Subsonic API](http://www.subsonic.org/pages/api.jsp) on the server, so that any of the existing Subsonic Android or iOS apps can seamlessly connect to Sonerezh. Some examples of polished Subsonic Android apps:

-    [Dsub](https://play.google.com/store/apps/details?id=github.daneren2005.dsub&hl=en)
-    [Madsonic](https://play.google.com/store/apps/details?id=github.madmarty.madsonic&hl=en)
-    [Subsonic](https://play.google.com/store/apps/details?id=net.sourceforge.subsonic.androidapp&hl=en)

**Comment by lGuillaume124** [comment]
We already discussed about the Subsonic API and we definitely don't think it is elegant... We prefer to develop our own API, which will exactly fit to Sonerezh, in the fastest way we can.

**Comment by asmartin** [comment]
That makes sense. One feature that I think the Subsonic mobile apps like DSub implement really well, and that I think would be a great feature for Sonerezh, is caching of songs (for offline/local play). You can either select specific songs/artists/albums and cache them to your device or (even better) anything you listen to is automatically cached. This is really nice for both when you are without data and also for reducing your data usage (e.g you often play your favorite songs from the local cache rather than streaming them again and again).

**Comment by lGuillaume124** [comment]
Yes, we'd like to propose something like that. You could also prepare your playlists on the web UI, and download them on the mobile app :)
We always keep in mind that Sonerezh must be as light as we can, mostly on mobile.

**Comment by khromov** [comment]
+1 on supporting the Subsonic API. The API may not elegant but an implementation would instantly give Sonerezh support over all the major mobile platforms - High-quality Android, iPhone and Windows Phone apps are available. 

I'm in favor of having your own API as well, but the biggest bang for the buck would to implement the Subsonic one first.
